language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: checks
      install: npm install
      script: npm run check
    - stage: deploy
      branches:
        only:
        - V2
      install: npm install
      script: npm run build
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
        bucket: dynamiclandscape
        acl: public_read
        region: eu-central-1
        skip_cleanup: true
        local_dir: build
        on:
          repo: MaibornWolff/dynamic-landscape
          branch: V2
